#!/bin/bash

# Move to this script's directory
cd "$(dirname "$0")" || return

BASE_URL="$(./base-url)"

TOKEN="$1"

if [ $# -ge 1 ] ; then
    curl \
      --include \
      --request DELETE  \
      --header "Content-Type: application/json" \
      "$BASE_URL"/fcm/tokens/"$TOKEN"
else
    echo "Usage: ./1-delete-token TOKEN"
fi
