#!/bin/bash

cd "$(dirname "$0")" || return
BASE_URL="$(./base-url)"

FIRSTNAME="$1"
LASTNAME="$2"

if [ $# -ge 2 ] ; then
    curl \
      --include \
      --request POST  \
      --header "Content-Type: application/json" \
      --data '
    {
      "firstName": "'"$FIRSTNAME"'",
      "lastName": "'"$LASTNAME"'"
    }' \
      "$BASE_URL"/path
else
    echo "Usage: ./test firstname lastname"
fi
